import { signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Parser from "papaparse";
// import { useRouter } from "next/router";
import { ChangeEvent, useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { data: session } = useSession();
  const [data, setData] = useState([]);
  // const router = useRouter();

  const changeHandler = (event: ChangeEvent<HTMLInputElement>) => {
    if (!event.target || !event.target.files) return;
    console.log(event.target.files[0]);

    Parser.parse(event.target.files[0], {
      header: true,
      skipEmptyLines: true,
      complete: function (results) {
        console.log(results.data);
        const newData = results.data.sort((a: any, b: any) =>
          a["# of Courses Completed"] < b["# of Courses Completed"] ? 1 : -1
        );
        setData(newData as any);
      },
    });
  };

  if (data) {
    console.log(data);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {session && (
        <div className={styles.container}>
          <h1>Upload</h1>
          <button
            onClick={() => signOut()}
            style={{ display: "block", margin: "50px" }}
          >
            Sign out
          </button>
          <input
            type="file"
            name="file"
            accept=".csv"
            style={{ marginBottom: "20px" }}
            onChange={changeHandler}
          />
        </div>
      )}
      <table border={2} cellPadding={5}>
        <thead>
          <tr>
            <th>Sl. No.</th>
            <th>Student Name</th>
            <th>Student Email</th>
            <th># Courses Completed</th>
          </tr>
        </thead>
        <tbody>
          {data.map((item: any, index) => (
            <tr key={index}>
              <td>{index + 1}</td>
              <td>
                <a href={item["Google Cloud Skills Boost Profile URL"]}>
                  {item["Student Name"]}
                </a>
              </td>
              <td>{item["Student Email"]}</td>
              <td>{item["# of Courses Completed"]}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
