import fs from "fs";
import path from "path";
import Head from "next/head";
import Parser from "csv-parser";

export default function Home(props: any) {
  const { data, errors, meta } = props;

  return (
    <div className="">
      <Head>
        <title>GCCP 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <h1>GCCP 2022 Status</h1>
      </div>
      <div className="overflow-x-auto relative">
        <table className="w-full text-sm text-left text-gray-500 dark:text-gray-400">
          <thead className="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
              <th scope="col" className="py-3 px-6">
                Sl. No.
              </th>
              <th scope="col" className="py-3 px-6">
                Student Name
              </th>
              <th scope="col" className="py-3 px-6">
                Student Email
              </th>
              <th scope="col" className="py-3 px-6">
                # Courses Completed
              </th>
              <th scope="col" className="py-3 px-6">
                Completion Status
              </th>
            </tr>
          </thead>
          <tbody>
            {data?.map((item: any, index: number) => (
              <tr
                key={index}
                className="bg-white border-b dark:bg-gray-800 dark:border-gray-700"
              >
                <td
                  scope="row"
                  className="py-4 px-6 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                >
                  {index + 1}
                </td>
                <td className="py-4 px-6 hover:text-red-200">
                  <a href={item["Google Cloud Skills Boost Profile URL"]}>
                    {item["Student Name"]}
                  </a>
                </td>
                <td className="py-4 px-6">{item["Student Email"]}</td>
                <td className="py-4 px-6">{item["# of Courses Completed"]}</td>
                <td className="py-4 px-6">
                  {item["Learning Path Completion Status"]}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const getData = async (location: string) => {
    return new Promise((resolve, reject) => {
      const results: any[] = [];
      fs.createReadStream(location)
        .pipe(Parser())
        .on("data", (data) => results.push(data))
        .on("end", () => {
          console.log("CSV file successfully processed");
          resolve(results);
        })
        .on("error", (error) => {
          console.log("Error while processing CSV file");
          console.log(error);
          reject(error);
        });
    });
  };

  const fileName =
    process.env.NODE_ENV === "development" ? "sample.csv" : "last-updated.csv";

  const fileLocation = path.join(process.cwd(), `data/${fileName}`);
  const res = await getData(fileLocation);
  const data = (res as any).sort((a: any, b: any) => {
    const criteria = "# of Courses Completed";
    return a[criteria] < b[criteria] ? 1 : -1;
  });

  return {
    props: {
      data: data,
    },
  };
}
